apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-new-ns-mar1224-development
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/go-new-ns-mar1224/overlays/development
    repoURL: https://github.com/testjc1/go-new-ns-mar1224-gitops.git
    targetRevision: main
  destination:
    namespace: new-ns-development
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
