apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-new-ns-mar1224
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-new-ns-mar1224 
  name: go-new-ns-mar1224
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-new-ns-mar1224 
